'use client';

import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {Sparkles} from 'lucide-react';
import {post} from '../../lib/api';

function Logo(){return <div className="mb-6 flex items-center gap-3"><span className="flex h-6 items-end gap-0.5"><i className="block w-1 rounded bg-[var(--accent)]" style={{height:10}}/><i className="block w-1 rounded bg-[var(--accent)]" style={{height:22}}/><i className="block w-1 rounded bg-[var(--accent)]" style={{height:14}}/></span><h1 className="text-3xl font-bold">SignalSort AI</h1></div>}

export default function Login(){const r=useRouter(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);async function submit(e:any){e.preventDefault();setLoading(true);try{const x=await post('/auth/login',{email,password});localStorage.setItem('token',x.token);r.push('/dashboard')}catch(e:any){setError(e.message)}finally{setLoading(false)}}return <main className="grid min-h-dvh place-items-center bg-[var(--bg)] p-5 text-[var(--text)]"><div className="w-full max-w-md"><Logo/><p className="muted mb-6 text-lg">Find meaningful signals in busy communities.</p><div className="card mb-4 text-sm"><div className="flex items-start gap-3"><Sparkles className="mt-0.5 text-[var(--accent)]" size={19}/><div><b>Demo access</b><p className="muted">demo@signalsort.ai / Demo@1234</p><button className="secondary mt-3 min-h-0 px-3 py-2 text-sm" onClick={()=>{setEmail('demo@signalsort.ai');setPassword('Demo@1234')}}>Fill demo credentials</button></div></div></div><form className="panel space-y-3" onSubmit={submit}><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="rounded-lg bg-rose-500/10 p-3 text-rose-200">{error}</p>}<button className="primary w-full" disabled={loading}>{loading?'Waking up server...':'Log in'}</button></form></div></main>}
