'use client';

import {useEffect,useState} from 'react';
import {Plus,Target,Trash2} from 'lucide-react';
import Shell from '../../components/Shell';
import {api,post} from '../../lib/api';

const examples=['Looking for healthcare tech projects to contribute to','Internships or jobs in data science and AI','Hackathons, fellowships, and scholarships'];

export default function Intents(){const [items,setItems]=useState<any[]>([]),[title,setTitle]=useState(''),[description,setDescription]=useState(''),[threshold,setThreshold]=useState(.5);const load=()=>{void api('/intents').then(setItems)};useEffect(()=>{load()},[]);async function add(e:any){e.preventDefault();await post('/intents',{title,description,threshold,is_active:true});setTitle('');setDescription('');load()}return <Shell><div className="mb-6"><h2 className="text-2xl font-bold md:text-[28px]">Listening intents</h2><p className="muted mt-1">Tell SignalSort what to watch for across noisy communities.</p></div><div className="grid gap-6 lg:grid-cols-[minmax(260px,40fr)_minmax(0,60fr)]"><section className="space-y-3">{items.map(i=><article className="card border-l-[3px] border-l-[var(--accent)]" key={i.id}><div className="flex items-start gap-3"><Target className="mt-0.5 shrink-0 text-[var(--accent)]" size={19}/><div className="min-w-0 flex-1"><b>{i.title}</b><p className="muted mt-1 text-sm">{i.description}</p><p className="mono muted mt-2 text-xs">Threshold {Math.round((i.threshold||0)*100)}%</p></div><button className="secondary min-h-0 px-2 py-2 text-rose-300" title="Delete intent" onClick={async()=>{await api(`/intents/${i.id}`,{method:'DELETE'});load()}}><Trash2 size={16}/></button></div></article>)}{!items.length&&<div className="card text-center"><Target className="mx-auto mb-3 text-[var(--accent)]" size={30}/><p className="muted">No intents yet. Create one to start matching.</p></div>}</section><section className="panel"><form className="space-y-4" onSubmit={add}><div><label className="mb-2 block text-sm font-medium">Title</label><input placeholder="What are you listening for?" value={title} onChange={e=>setTitle(e.target.value)}/></div><div><label className="mb-2 block text-sm font-medium">Description</label><textarea placeholder="Describe the projects, skills, roles, or opportunities you want" value={description} onChange={e=>setDescription(e.target.value)}/><p className="muted mt-2 text-sm">Be specific. Name the skills, topics, or roles you care about.</p></div><label className="block text-sm font-medium">Strictness <span className="mono text-[var(--accent)]">{Math.round(threshold*100)}%</span><input className="mt-3" type="range" min="0" max="1" step=".05" value={threshold} onChange={e=>setThreshold(+e.target.value)}/></label><div className="muted flex justify-between text-xs"><span>Loose</span><span>Balanced</span><span>Strict</span></div><button className="primary"><Plus size={17}/>Create intent</button></form><div className="mt-5 flex flex-wrap gap-2">{examples.map(example=><button className="secondary min-h-0 rounded-full px-3 py-2 text-sm" key={example} onClick={()=>{setTitle(example);setDescription(example)}}>{example}</button>)}</div></section></div></Shell>}
